version: '3'
services:
  server:
    build: 
      context: ./server/
      dockerfile: Dockerfile.dev
    ports:
      - "9000:9000"
    volumes:
      - /app/node_modules
      - ./server:/app
  client:
    build: 
      context: ./client_react_apollo/
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./client_react_apollo:/app
  
   